function varargout = cognitive_radio(varargin)
% COGNITIVE_RADIO MATLAB code for cognitive_radio.fig
%      COGNITIVE_RADIO,  by itself,  creates a new COGNITIVE_RADIO or raises the existing
%      singleton*.
%
%      H = COGNITIVE_RADIO returns the handle to a new COGNITIVE_RADIO or the handle to
%      the existing singleton*.
%
%      COGNITIVE_RADIO('CALLBACK', hObject, eventData, handles, ...) calls the local
%      function named CALLBACK in COGNITIVE_RADIO.M with the given input arguments.
%
%      COGNITIVE_RADIO('Property', 'Value', ...) creates a new COGNITIVE_RADIO or raises the
%      existing singleton*.  Starting from the left,  property value pairs are
%      applied to the GUI before cognitive_radio_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to cognitive_radio_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE,  GUIDATA,  GUIHANDLES

% Edit the above text to modify the response to help cognitive_radio

% Last Modified by GUIDE v2.5 14-May-2018 12:03:34

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',        mfilename,  ...
    'gui_Singleton',   gui_Singleton,  ...
    'gui_OpeningFcn',  @cognitive_radio_OpeningFcn,  ...
    'gui_OutputFcn',   @cognitive_radio_OutputFcn,  ...
    'gui_LayoutFcn',  @cognitive_radio_LayoutFcn, ...
    'gui_Callback',    []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State,  varargin{:});
else
    gui_mainfcn(gui_State,  varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before cognitive_radio is made visible.
function cognitive_radio_OpeningFcn(hObject,  eventdata,  handles,  varargin)
% This function has no output args,  see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to cognitive_radio (see VARARGIN)

% Choose default command line output for cognitive_radio
handles.output = hObject;

% Update handles structure
guidata(hObject,  handles);

% UIWAIT makes cognitive_radio wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = cognitive_radio_OutputFcn(hObject,  eventdata,  handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;


% --- Executes on button press in pushbutton3.
function pushbutton3_Callback(hObject,  eventdata,  handles)
% hObject    handle to pushbutton3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
project_name = get(handles.edit1, 'String');
suggestion = strcat(project_name, '.cr');
[filename,  pathname] = uiputfile({'*.cr'}, 'Save Project', suggestion);
file = fullfile(pathname, filename);
filepath_database = get(handles.edit2, 'String');
[~,  filename,  ext] = fileparts(filepath_database);
csvwrite(strcat(pathname,  filename,  ext),  handles.fileData);
contents = get(handles.popupmenu1, 'String');
type = contents{get(handles.popupmenu1, 'Value')};
traffic_level = get(get(handles.uibuttongroup1, 'SelectedObject'), 'String');
fileID = fopen(file, 'w');
fprintf(fileID, '%s\n', project_name);
fprintf(fileID, '%s\n', strcat(filename, ext));
fprintf(fileID, '%s\n', type);
fprintf(fileID, '%s\n', traffic_level);
fclose(fileID);


function edit4_Callback(hObject,  eventdata,  handles)
% hObject    handle to edit4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject, 'String') returns contents of edit4 as text
%        str2double(get(hObject, 'String')) returns contents of edit4 as a double


% --- Executes during object creation,  after setting all properties.
function edit4_CreateFcn(hObject,  eventdata,  handles)
% hObject    handle to edit4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject, 'BackgroundColor'),  get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'white');
end



function edit6_Callback(hObject,  eventdata,  handles)
% hObject    handle to edit6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject, 'String') returns contents of edit6 as text
%        str2double(get(hObject, 'String')) returns contents of edit6 as a double


% --- Executes during object creation,  after setting all properties.
function edit6_CreateFcn(hObject,  eventdata,  handles)
% hObject    handle to edit6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject, 'BackgroundColor'),  get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'white');
end



function edit5_Callback(hObject,  eventdata,  handles)
% hObject    handle to edit5 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject, 'String') returns contents of edit5 as text
%        str2double(get(hObject, 'String')) returns contents of edit5 as a double


% --- Executes during object creation,  after setting all properties.
function edit5_CreateFcn(hObject,  eventdata,  handles)
% hObject    handle to edit5 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject, 'BackgroundColor'),  get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'white');
end


% --- Executes on button press in pushbutton2.
function pushbutton2_Callback(hObject,  eventdata,  handles)
% hObject    handle to pushbutton2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
full_path = get(handles.edit2, 'String');
file_data = csvread(full_path);
num_towers = str2num(get(handles.edit7, 'String'));
type_model = get(get(handles.uibuttongroup2, 'SelectedObject'), 'String');
if strcmp(type_model, 'SVM')
    svm_type = get(handles.popupmenu2, 'Value') - 1;
    kernel_type = get(handles.popupmenu3, 'Value') - 1;
    cost = get(handles.edit14, 'String');
    options = sprintf('-s %d -t %d -c %s -q', svm_type, kernel_type, cost);
    tic;
    [towers, accuracy, error] = train_svm_model(file_data, num_towers, options);
    time = toc;
    set(handles.listbox1, 'String', accuracy);
    set(handles.listbox2, 'String', error);
    set(handles.edit15, 'String', time);
else
    NumMf = str2num(get(handles.numberMF_e, 'String'))    
    MfType = char(split(erase(get(handles.MFtype_e,'String'),"'"),','))
    epochs = str2num(get(handles.edit12, 'String'))
    tic;
    [fis_mat,trn_err,chk_err] = train_anfis_mode(file_data, NumMf,MfType, epochs, num_towers);
    time = toc;
end

function edit1_Callback(hObject,  eventdata,  handles)
% hObject    handle to edit1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject, 'String') returns contents of edit1 as text
%        str2double(get(hObject, 'String')) returns contents of edit1 as a double


% --- Executes during object creation,  after setting all properties.
function edit1_CreateFcn(hObject,  eventdata,  handles)
% hObject    handle to edit1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject, 'BackgroundColor'),  get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'white');
end


% --- Executes on selection change in popupmenu1.
function popupmenu1_Callback(hObject,  eventdata,  handles)
% hObject    handle to popupmenu1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject, 'String')) returns popupmenu1 contents as cell array
%        contents{get(hObject, 'Value')} returns selected item from popupmenu1


% --- Executes during object creation,  after setting all properties.
function popupmenu1_CreateFcn(hObject,  eventdata,  handles)
% hObject    handle to popupmenu1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject, 'BackgroundColor'),  get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'white');
end



function edit2_Callback(hObject,  eventdata,  handles)
% hObject    handle to edit2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject, 'String') returns contents of edit2 as text
%        str2double(get(hObject, 'String')) returns contents of edit2 as a double


% --- Executes during object creation,  after setting all properties.
function edit2_CreateFcn(hObject,  eventdata,  handles)
% hObject    handle to edit2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject, 'BackgroundColor'),  get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'white');
end


% --- Executes on button press in pushbutton1.
function pushbutton1_Callback(hObject,  eventdata,  handles)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
[filename,  pathname] = uigetfile({'*.csv'}, 'Open Directory');
if isequal(filename, 0) || isequal(pathname, 0)
    return
end
set(handles.edit2,  'String',  strcat(pathname,  filename));
file = fullfile(pathname,  filename);
handles.fileData = csvread(file);
guidata(hObject,  handles);


% --- Executes on button press in pushbutton4.
function pushbutton4_Callback(hObject,  eventdata,  handles)
% hObject    handle to pushbutton4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)



function edit7_Callback(hObject, eventdata, handles)
% hObject    handle to edit7 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit7 as text
%        str2double(get(hObject,'String')) returns contents of edit7 as a double


% --- Executes during object creation, after setting all properties.
function edit7_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit7 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit8_Callback(hObject, eventdata, handles)
% hObject    handle to edit8 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit8 as text
%        str2double(get(hObject,'String')) returns contents of edit8 as a double


% --- Executes during object creation, after setting all properties.
function edit8_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit8 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function numberMF_e_Callback(hObject, eventdata, handles)
% hObject    handle to numberMF_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of numberMF_e as text
%        str2double(get(hObject,'String')) returns contents of numberMF_e as a double


% --- Executes during object creation, after setting all properties.
function numberMF_e_CreateFcn(hObject, eventdata, handles)
% hObject    handle to numberMF_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function MFtype_e_Callback(hObject, eventdata, handles)
% hObject    handle to MFtype_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of MFtype_e as text
%        str2double(get(hObject,'String')) returns contents of MFtype_e as a double


% --- Executes during object creation, after setting all properties.
function MFtype_e_CreateFcn(hObject, eventdata, handles)
% hObject    handle to MFtype_e (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in radiobutton4.
function radiobutton4_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: get(hObject,'Value') returns toggle state of radiobutton4
set(handles.panelANFIS, 'Visible', 'off');
set(handles.panelSVM, 'Visible', 'on');


% --- Executes on button press in radiobutton5.
function radiobutton5_Callback(hObject, eventdata, handles)
% hObject    handle to radiobutton5 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: get(hObject,'Value') returns toggle state of radiobutton5
set(handles.panelSVM, 'Visible', 'off');
set(handles.panelANFIS, 'Visible', 'on');


% --- Executes on selection change in popupmenu2.
function popupmenu2_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu2 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu2


% --- Executes during object creation, after setting all properties.
function popupmenu2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in popupmenu3.
function popupmenu3_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu3 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu3


% --- Executes during object creation, after setting all properties.
function popupmenu3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit14_Callback(hObject, eventdata, handles)
% hObject    handle to edit14 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit14 as text
%        str2double(get(hObject,'String')) returns contents of edit14 as a double


% --- Executes during object creation, after setting all properties.
function edit14_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit14 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit12_Callback(hObject, eventdata, handles)
% hObject    handle to edit12 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit12 as text
%        str2double(get(hObject,'String')) returns contents of edit12 as a double


% --- Executes during object creation, after setting all properties.
function edit12_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit12 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit15_Callback(hObject, eventdata, handles)
% hObject    handle to edit15 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit15 as text
%        str2double(get(hObject,'String')) returns contents of edit15 as a double


% --- Executes during object creation, after setting all properties.
function edit15_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit15 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit16_Callback(hObject, eventdata, handles)
% hObject    handle to edit16 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit16 as text
%        str2double(get(hObject,'String')) returns contents of edit16 as a double


% --- Executes during object creation, after setting all properties.
function edit16_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit16 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit17_Callback(hObject, eventdata, handles)
% hObject    handle to edit17 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit17 as text
%        str2double(get(hObject,'String')) returns contents of edit17 as a double


% --- Executes during object creation, after setting all properties.
function edit17_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit17 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in listbox1.
function listbox1_Callback(hObject, eventdata, handles)
% hObject    handle to listbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject,'String')) returns listbox1 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from listbox1


% --- Executes during object creation, after setting all properties.
function listbox1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to listbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in listbox2.
function listbox2_Callback(hObject, eventdata, handles)
% hObject    handle to listbox2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject,'String')) returns listbox2 contents as cell array
%        contents{get(hObject,'Value')} returns selected item from listbox2


% --- Executes during object creation, after setting all properties.
function listbox2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to listbox2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton5.
function pushbutton5_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton5 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
message = sprintf('The availables functions are:\n \t trimf\n \t trapmf\n \t gaussmf\n \t gauss2mf\n \t gbellmf\n \t sigmf\n \t dsigmf\n \t psigmf\n \t zmf\n \t pimf\n \t smf\n');
msgbox(message,'Available Functions');


% --- Creates and returns a handle to the GUI figure. 
function h1 = cognitive_radio_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load cognitive_radio.mat


appdata = [];
appdata.GUIDEOptions = mat{1};
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'PaperUnits','inches',...
'Units','characters',...
'Position',[135.8 55.6971153846154 103.857142857143 28.6875],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','interface',...
'NumberTitle','off',...
'Tag','figure1',...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',[8.5 11],...
'PaperSizeMode',get(0,'defaultfigurePaperSizeMode'),...
'PaperType','usletter',...
'PaperTypeMode',get(0,'defaultfigurePaperTypeMode'),...
'PaperUnitsMode',get(0,'defaultfigurePaperUnitsMode'),...
'ScreenPixelsPerInchMode','manual',...
'HandleVisibility','callback',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel1';

h2 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Project name and project location',...
'Tag','uipanel1',...
'Position',[1.57142857142857 16.0625 101.714285714286 11.8125],...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuipanelFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text3';

h3 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','Project name',...
'Style','text',...
'Position',[3.2 8.96634615384615 17 1.07692307692308],...
'Children',[],...
'Tag','text3',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'edit1';

h4 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','edit',...
'Position',[23.4285714285714 8.90865384615384 60.4285714285714 1.25],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)cognitive_radio('edit1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('edit1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edit1',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'text4';

h5 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','Load database',...
'Style','text',...
'Position',[2.8 6.96634615384615 17.6 1.07692307692308],...
'Children',[],...
'Tag','text4',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'popupmenu1';

h6 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'Wi-Fi'; 'GSM' },...
'Style','popupmenu',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[23.1428571428571 4.4375 76.8571428571428 1.5625],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)cognitive_radio('popupmenu1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('popupmenu1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','popupmenu1',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'edit2';

h7 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String',blanks(0),...
'Style','edit',...
'Position',[23.2857142857143 6.65865384615384 60.5714285714286 1.3125],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)cognitive_radio('edit2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('edit2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edit2',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'pushbutton1';

h8 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','.....',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[85.8571428571428 6.4375 14 1.6875],...
'Callback',@(hObject,eventdata)cognitive_radio('pushbutton1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pushbutton1',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uibuttongroup1';

h9 = uibuttongroup(...
'Parent',h2,...
'FontUnits','points',...
'Units','characters',...
'Title','Traffic Level',...
'Tag','uibuttongroup1',...
'Position',[1.85714285714286 0.5625 98.1428571428571 3.375],...
'FontSize',8,...
'FontSizeMode','auto',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'radiobutton1';

h10 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','High Traffic',...
'Style','radiobutton',...
'Value',1,...
'Position',[5.8 0.60576923076923 17 1.76923076923077],...
'Children',[],...
'Tag','radiobutton1',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'radiobutton2';

h11 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Medium Traffic',...
'Style','radiobutton',...
'Position',[40.8 0.60576923076923 20.2 1.76923076923077],...
'Children',[],...
'Tag','radiobutton2',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'radiobutton3';

h12 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Lower Traffic',...
'Style','radiobutton',...
'Position',[77.4 0.60576923076923 19.4 1.76923076923077],...
'Children',[],...
'Tag','radiobutton3',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text14';

h13 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment','left',...
'String','Type',...
'Style','text',...
'Position',[3 4.65865384615384 17 1.07692307692308],...
'Children',[],...
'Tag','text14',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton4';

h14 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','IMPORT',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[85.8571428571428 8.78365384615384 14.1428571428571 1.6875],...
'Callback',@(hObject,eventdata)cognitive_radio('pushbutton4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton4',...
'KeyPressFcn',blanks(0),...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'uipanel2';

h15 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','ProJect Control',...
'Tag','uipanel2',...
'Position',[1.85714285714286 7.25 101.142857142857 8.875],...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuipanelFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uibuttongroup2';

h16 = uibuttongroup(...
'Parent',h15,...
'FontUnits','points',...
'Units','characters',...
'Title','Model',...
'Tag','uibuttongroup2',...
'Position',[1 4.25 34.7142857142857 3.375],...
'FontSize',8,...
'FontSizeMode','auto',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'radiobutton4';

h17 = uicontrol(...
'Parent',h16,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','SVM',...
'Style','radiobutton',...
'Value',1,...
'Position',[3.57142857142857 0.75 10.1428571428571 1.75],...
'Callback',@(hObject,eventdata)cognitive_radio('radiobutton4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','radiobutton4',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'radiobutton5';

h18 = uicontrol(...
'Parent',h16,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','ANFIS',...
'Style','radiobutton',...
'Position',[20.2857142857143 0.6875 12 1.75],...
'Callback',@(hObject,eventdata)cognitive_radio('radiobutton5_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','radiobutton5',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'panelANFIS';

h19 = uipanel(...
'Parent',h15,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Structure',...
'Tag','panelANFIS',...
'Position',[1.42857142857143 0.875 97.7142857142857 3.25],...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuipanelFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'numMF';

h20 = uicontrol(...
'Parent',h19,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Number of MF',...
'Style','text',...
'Position',[2 1.0625 14 0.8125],...
'Children',[],...
'Interruptible','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','numMF',...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'numberMF_e';

h21 = uicontrol(...
'Parent',h19,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[16.1428571428571 0.8125 14.5714285714286 1.25],...
'Callback',@(hObject,eventdata)cognitive_radio('numberMF_e_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('numberMF_e_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','numberMF_e',...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'MFType';

h22 = uicontrol(...
'Parent',h19,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','MF type',...
'Style','text',...
'Position',[34.8571428571429 1.0625 7.42857142857143 0.8125],...
'Children',[],...
'Tag','MFType',...
'FontSize',8,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'MFtype_e';

h23 = uicontrol(...
'Parent',h19,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[42 0.8125 16 1.25],...
'Callback',@(hObject,eventdata)cognitive_radio('MFtype_e_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('MFtype_e_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','MFtype_e',...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'text22';

h24 = uicontrol(...
'Parent',h19,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Iterations',...
'Style','text',...
'Position',[71.7142857142857 0.875 10.4285714285714 1.0625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text22',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'edit12';

h25 = uicontrol(...
'Parent',h19,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[83.4285714285714 0.8125 8.14285714285714 1.375],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)cognitive_radio('edit12_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('edit12_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','edit12',...
'KeyPressFcn',blanks(0),...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'pushbutton5';

h26 = uicontrol(...
'Parent',h19,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','?',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[58.5714285714286 0.6875 5 1.5625],...
'Callback',@(hObject,eventdata)cognitive_radio('pushbutton5_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pushbutton5',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'edit7';

h27 = uicontrol(...
'Parent',h15,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[63.8571428571429 5.4375 7.71428571428572 1.3125],...
'Callback',@(hObject,eventdata)cognitive_radio('edit7_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('edit7_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','edit7',...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'text16';

h28 = uicontrol(...
'Parent',h15,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Number of towers',...
'Style','text',...
'Position',[45.1428571428571 5.5 17 1.0625],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text16',...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'pushbutton2';

h29 = uicontrol(...
'Parent',h15,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','RUN',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[85 5.25 13.8571428571429 1.6875],...
'Callback',@(hObject,eventdata)cognitive_radio('pushbutton2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pushbutton2',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel3';

h30 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Results',...
'Tag','uipanel3',...
'Position',[2 0.4375 100.714285714286 6.875],...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuipanelFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text8';

h31 = uicontrol(...
'Parent',h30,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Time (s):',...
'Style','text',...
'Position',[1 4.1875 8.28571428571428 1.0625],...
'Children',[],...
'Tag','text8',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text12';

h32 = uicontrol(...
'Parent',h30,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Accurancy:',...
'Style','text',...
'Position',[18.4285714285714 4.125 10.4285714285714 1.0625],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text12',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'pushbutton3';

h33 = uicontrol(...
'Parent',h30,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','EXPORT',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[84.8571428571428 3.75 13.8571428571429 1.6875],...
'Callback',@(hObject,eventdata)cognitive_radio('pushbutton3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','pushbutton3',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'edit15';

h34 = uicontrol(...
'Parent',h30,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[9.57142857142857 4.0625 7.71428571428571 1.3125],...
'Callback',@(hObject,eventdata)cognitive_radio('edit15_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('edit15_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','edit15',...
'KeyPressFcn',blanks(0),...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'listbox1';

h35 = uicontrol(...
'Parent',h30,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','listbox',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[29.7142857142857 0.625 20.8571428571429 4.8125],...
'Callback',@(hObject,eventdata)cognitive_radio('listbox1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('listbox1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','listbox1');

appdata = [];
appdata.lastValidTag = 'text26';

h36 = uicontrol(...
'Parent',h30,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Mean Square Error:',...
'Style','text',...
'Position',[52.1428571428571 2.125 10.4285714285714 3.25],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text26',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'listbox2';

h37 = uicontrol(...
'Parent',h30,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','listbox',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[63.5714285714286 0.625 19.8571428571429 4.8125],...
'Callback',@(hObject,eventdata)cognitive_radio('listbox2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('listbox2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','listbox2',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'panelSVM';

h38 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Structure',...
'Tag','panelSVM',...
'Position',[3.28571428571429 8.1875 97.8571428571428 3.3125],...
'FontSize',8,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'popupmenu2';

h39 = uicontrol(...
'Parent',h38,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'C-SVC'; 'nu-SVC'; 'one-class'; 'epsilon-SVR'; 'nu-SVR' },...
'Style','popupmenu',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[14.1428571428571 0.75 12.5714285714286 1.375],...
'Callback',@(hObject,eventdata)cognitive_radio('popupmenu2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('popupmenu2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','popupmenu2',...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'text23';

h40 = uicontrol(...
'Parent',h38,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Type',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[2.42857142857143 1.125 10.2857142857143 0.8125],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'ButtonDownFcn',blanks(0),...
'Interruptible','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text23',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text24';

h41 = uicontrol(...
'Parent',h38,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Kernel Type',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[39.4285714285714 0.9375 10.2857142857143 0.8125],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'ButtonDownFcn',blanks(0),...
'Interruptible','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text24',...
'UserData',[],...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'popupmenu3';

h42 = uicontrol(...
'Parent',h38,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',{  'linear'; 'polynomial'; 'radial basis'; 'sigmoid' },...
'Style','popupmenu',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[50.1428571428571 0.75 12.5714285714286 1.375],...
'Callback',@(hObject,eventdata)cognitive_radio('popupmenu3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('popupmenu3_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','popupmenu3',...
'KeyPressFcn',blanks(0),...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'edit14';

h43 = uicontrol(...
'Parent',h38,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','1',...
'Style','edit',...
'Position',[87.2857142857143 0.9375 7.71428571428571 1.3125],...
'Callback',@(hObject,eventdata)cognitive_radio('edit14_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)cognitive_radio('edit14_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','edit14',...
'KeyPressFcn',blanks(0),...
'FontSize',8);

appdata = [];
appdata.lastValidTag = 'text25';

h44 = uicontrol(...
'Parent',h38,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Cost',...
'Style','text',...
'Position',[76.2857142857143 1 9.85714285714286 1.0625],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text25',...
'FontSize',8);


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % COGNITIVE_RADIO
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % COGNITIVE_RADIO(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % COGNITIVE_RADIO('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % COGNITIVE_RADIO(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


